### PR TITLE
Fix BG1 and SoD NPC voicesets.

### PR DESCRIPTION
**Pull request by GraionDilach**
Relies on 2.6 enabling unused sound slots. Also removed changes where BG1 lines were overwritten, only keeping the changes where empty slots were populated.

### CODE REVIEW

**Comment by Blash** [comment]
Are you seriously telling me I'll finally be able to keep my BG1 characters voices through all EET? 😃
I remember that when moving to the SoD part of EET, the voices of my characters changed, causing a break of immersion.

**Comment by GraionDilach** [comment]
> I remember that when moving to the SoD part of EET, the voices of my characters changed, causing a break of immersion.

No, changing the soundsets during BGEE->SoD transition is by Beamdog design and changing the soundsets during SoD->BG2EE transition is consistent with BGT (which even predates the Beamdog decision). That is the correct behaviour and freezing the soundsets should be done in an external mod.

This PR restores the 9-click on selection "rare select" responses on BGEE/SoD NPCs. There is a bit of immersion-breaking related to it fixed here, because currently SoD NPCs in EET use their rare select responses as regular action responses.

**Comment by Blash** [comment]
> > I remember that when moving to the SoD part of EET, the voices of my characters changed, causing a break of immersion.
> 
> No, changing the soundsets during BGEE->SoD transition is by Beamdog design and changing the soundsets during SoD->BG2EE transition is consistent with BGT (which even predates the Beamdog decision). That is the correct behaviour and freezing the soundsets should be done in an external mod.
> 
> This PR restores the 9-click on selection "rare select" responses on BGEE/SoD NPCs. There is a bit of immersion-breaking related to it fixed here, because currently SoD NPCs in EET use their rare select responses as regular action responses. (There are actual action responses for these NPCs which they could use instead, but I'm already restoring those in the EE Fixpack already.)

Is there any known way to keep BG1 soundset during all of EET? I remember that in the EET Tweak Pack there was this possibility for the Polish version (because, IIRC, the voice over actors changed and that broke immersion). @K4thos would you consider adding this option? Suddenly hearing my NPCs voices change might be consistent even with BGT but surely breaks immersion.

**Comment by GraionDilach** [comment]
AC's Miscellaneous Tweaks include a component to use the SoD soundsets during BGEE. The BGForge Tweaks and Tricks mod includes a component doing this for the Bioware voicesets, although I never tested if it works on EET.

Note that there are cases when the character's voiceset changes within the game even (Neera's SoD voiceset changes when her personal quest is completed to get Adoy out of her head, Aerie and Nalia has some of their responses changed during SoA->ToB transition). And ofcourse there's Edwina.

In any case, such a component would belong to a tweakmod outside of EET. Maybe to EET Tweaks.

**Comment by Blash** [comment]
> AC's Miscellaneous Tweaks include a component to use the SoD soundsets during BGEE. The BGForge Tweaks and Tricks mod includes a component doing this for the Bioware voicesets, although I never tested if it works on EET.
> 
> Note that there are cases when the character's voiceset changes within the game even (Neera's SoD voiceset changes when her personal quest is completed to get Adoy out of her head, Aerie and Nalia has some of their responses changed during SoA->ToB transition). And ofcourse there's Edwina.
> 
> In any case, such a component would belong to a tweakmod outside of EET. Maybe to EET Tweaks.

Yes, that's why I mentioned @K4thos (I don't even know if he'll get a notification). He essentially already made such tweak for the Polish soundset, I suppose that adding an option for the English one might not require a big work.

Speaking of "The BGForge Tweaks and Tricks mod" I didn't even know it existed. It seems it might do what I need. I'll have a look, thank you very much!

**Comment by Blash** [comment]
Apparently I forgot I already extensively analyzed the matter, including the mod you mentioned:

https://www.gibberlings3.net/forums/topic/31274-consistent-soundset-for-eet/

And apparently it's still not tested for BGEE - SoD transition. My quest for a consistent soundset through all EET is far from being completed sadly.

**Pull request merged**
